name: Deploy Snowflake

on:
  push:
    branches:
      - main
      - test

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: snowflake_github_secrets

    steps:

      - uses: actions/checkout@v4

      - uses: snowflakedb/snowflake-cli-action@v2
        with:
          use-oidc: true
          cli-version: "3.16"

      - name: Test Connection
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: svc_github_oidc
        run: |
          snow connection test -x
